config/routes.rb
Rails.application.routes.draw do
  resources :lists
  get 'home/index'
  root 'home#index'

  devise_for :users
  resources :products
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_and_belongs_to_many :products, join_table: "items"
  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] || session[:locale] || I18n.default_locale
    I18n.locale = session[:locale]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    @products = Product.all
  end

  # GET /lists/1/edit
  def edit
    @products = Product.all
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :bought, :product_ids)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :error then "alert alert-error"
      when :alert then "alert alert-warning"
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
    <%= value %>

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      Pós
    </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= fa_icon 'home' %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div  id="menu" class="collapse navbar-collapse">
        <div class="navbar-nav mr-auto">
          <%= link_to t('products'), products_path, class: 'nav-item nav-link' %>
          <%= link_to t('lists'), lists_path, class: 'nav-item nav-link' %>
        </div>

        <div class="navbar-nav">
          <li class="nav-item dropdown">
            <a id="config" class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('menu') %>
            </a>
            <div class="dropdown-menu" aria-labelledby="config">
              <%= link_to 'pt-BR', root_path(locale: 'pt-BR'), class: 'dropdown-item' %>
              <%= link_to 'en', root_path(locale: 'en'), class: 'dropdown-item' %>

              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
              <% end %>
            </div>
          </li>
        </div>
      </div>
    </nav>

    <main class="container mt-2" role="main">
      <%= render 'flash' %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.label :bought %><br>
    <%= f.check_box :bought %>
    <%= f.association :products, as: :select, collection: @products %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>
  <%= t('editing', name: t('list.name', count: 1)) %>
</h1>

<%= render 'form' %>

<%= link_to t('show'), @list, class: 'btn btn-info', role: :button %>
<%= link_to t('index'), lists_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/lists/index.html.erb
<h1>
  <%= t('listing', name: t('list.name', count: 2)) %>
</h1>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th>
        <%= t('list.name', count: 2) %>
      </th>
      <th>
        <%= t('list.bought') %>
      </th>
      <th>
        <%= t('actions') %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td>
          <%= list.name %>
        </td>
        <td>
          <% if list.bought %>
            <%= t('list.bought') %>
          <% else %>
            <%= t('list.not_bought') %>
          <% end %>
        </td>
        <td>
          <div class="btn-group btn-group-sm" role="group">
            <%= link_to t('show'), list, class: 'btn btn-info', role: :button %>
            <%= link_to t('edit'), edit_list_path(list), class: 'btn btn-success', role: :button %>
            <%= link_to t('destroy'), list, method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-danger', role: :button %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new', name: t('list.name', count: 1)), new_list_path, class: 'btn btn-primary', role: :button %>

app/views/lists/new.html.erb
<h1>
  <%= t('new', name: t('list.name', count: 1)) %>
</h1>

<%= render 'form' %>

<%= link_to t('index'), lists_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/lists/show.html.erb
<h1>
  <%= t('listing', name: t('list.name', count: 1)) %>
</h1>

<table class="table table-striped table-hover">
  <tr>
    <th scope="row">
      <%= t('list.name', count: 1) %>:
    </th>
    <td>
      <%= @list.name %>
    </td>
  </tr>
  <tr>
    <th scope="row">
      <%= t('list.bought') %>:
    </th>
    <td>
      <% if @list.bought %>
        <%= t('list.bought') %>
      <% else %>
        <%= t('list.not_bought') %>
      <% end %>
    </td>
  </tr>
  <% @list.products.each do |product| -%>
  <tr>
    <th scope="row">
      <%= t('product.name', count: 1) %>:
    </th>
    <td>
      <%= product.name %>
    </td>
  </tr>
  <% end -%>
</table>

<%= link_to t('edit'), edit_list_path(@list), class: 'btn btn-primary', role: :button %>
<%= link_to t('index'), lists_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :avatar, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>
  <%= t('editing', name: t('product.name', count: 1)) %>
</h1>

<%= render 'form' %>

<br />

<%= link_to t('show'), @product, class: 'btn btn-info', role: :button %>
<%= link_to t('index'), products_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/products/index.html.erb
<h1>
  <%= t('listing', name: t('product.name', count: 2)) %>
</h1>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">
        <%= t('name') %>
      </th>
      <th scope="col">
        <%= t('actions') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.name %>
        </td>
        <td>
          <div class="btn-group btn-group-sm" role="group">
            <%= link_to product, class: 'btn btn-info', role: :button do %>
              <%= fa_icon 'search' %>
            <% end %>
            <%= link_to edit_product_path(product), class: 'btn btn-warning', role: :button do %>
              <%= fa_icon 'edit' %>
            <% end %>
            <%= link_to product, method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-danger', role: :button do %>
              <%= fa_icon 'trash' %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to t('new', name: t('product.name', count: 1)), new_product_path, class: 'btn btn-primary', role: :button %>

app/views/products/new.html.erb
<h1>
  <%= t('new', name: t('product.name', count: 1)) %>
</h1>

<%= render 'form' %>

<br />

<%= link_to t('index'), products_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/products/show.html.erb
<h1>
  <%= t('showing', name: t('product.name', count: 1)) %>
</h1>

<div class="card">
  <%= image_tag(@product.avatar_url, class: 'card-img-top') if @product.avatar? %>

  <div class="card-body">
    <h5 class="card-title">
      <%= @product.name %>
    </h5>

    <%= link_to t('edit'), edit_product_path(@product), class: 'btn btn-primary', role: :button %>
    <%= link_to t('index'), products_path, class: 'btn btn-outline-secondary', role: :button %>
  </div>
</div>